In [24]:
import numpy as np
import pandas as pd

In [25]:
folder_path = "/content/drive/MyDrive/Books_Recommender_System/"

In [26]:
import os

In [98]:
books = pd.read_csv(os.path.join(folder_path, "BX-Books.csv"), sep=";", error_bad_lines=False, encoding="latin-1")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [99]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [100]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [101]:
books = books[["ISBN", "Book-Title", "Book-Author", "Year-Of-Publication", "Publisher"]]

In [102]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [103]:
books.rename(columns={"Book-Title":"title", "Book-Author":"author", "Year-Of-Publication":"year","Publisher":"publisher"}, inplace=True)

In [104]:
books.head()

,ISBN,title,author,year,publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [105]:
users = pd.read_csv(os.path.join(folder_path, "BX-Users.csv"), sep=";", error_bad_lines=False, encoding="latin-1")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [106]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [107]:
users.rename(columns={"User-ID":"user_id", "Location":"location", "Age":"age"}, inplace=True)

In [108]:
users.head()

   user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [109]:
users.tail()

        user_id                            location   age
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

In [110]:
ratings = pd.read_csv(os.path.join(folder_path, "BX-Book-Ratings.csv"), sep=";", error_bad_lines=False, encoding="latin-1")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [111]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [112]:
ratings.rename(columns={"User-ID":"user_id", "Book-Rating":"rating"}, inplace=True)

In [113]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [114]:
books.shape

(271360, 5)

In [115]:
users.shape

(278858, 3)

In [116]:
ratings.shape

(1149780, 3)

# Approach

## Our Stategy to Collaborative Filtering

A user "A" and user "B" reads same book "book 1".<br>
User "A" also reads another book "book 2".<br>
Now our goal is to recommend book "book 2" to user "B".

We will create a matrix.
<br>
Rows will have Users.<br>
Columns will have Books.<br>
And we will save ratings.

# Filtering Data

Now since there are more than 2 lakh books and 2 lakh users. We can't train our model on every book and every user. Since some users who are not frequent readers don't give reliable ratings.

<br>

Similarly some books are either very new or unpopular. So we can't accept rating given to every book.

<br>

Although it can be achieved using trial and error.

We will consider only those users who have given minimum 200 ratings.

Similarly we will take only those books who have received minimum of 50 ratings.

In [117]:
ratings.head(2)

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5

In [118]:
ratings["user_id"].value_counts().shape

(105283,)

Only 1 lakh users out of 2 lakh have given ratings.

user given more than 200 ratings

In [119]:
x = ratings["user_id"].value_counts()>200

In [120]:
x

11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: user_id, Length: 105283, dtype: bool

In [121]:
x[x]

11676     True
198711    True
153662    True
98391     True
35859     True
          ...
274808    True
28634     True
59727     True
268622    True
188951    True
Name: user_id, Length: 899, dtype: bool

getting user ids

In [122]:
y = x[x].index

In [123]:
y.shape

(899,)

899 users gave more than 200 ratings

In [124]:
ratings["user_id"].isin(y)

0          False
1          False
2          False
3          False
4          False
           ...
1149775    False
1149776    False
1149777    False
1149778    False
1149779    False
Name: user_id, Length: 1149780, dtype: bool

In [125]:
ratings[ratings["user_id"].isin(y)]

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

above are ratings given by users who have given more than 200 ratings in total.

Storing it in new_Ratings

In [126]:
new_ratings = ratings[ratings["user_id"].isin(y)]

In [127]:
new_ratings.shape

(526356, 3)

2 Lakh user gave 11 lakh ratings

these 899 users gave more than 5 lakh ratings alone.

In [128]:
ratings_with_books = new_ratings.merge(books , on="ISBN")

In [129]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc

In [130]:
ratings_with_books.shape

(487671, 7)

In [131]:
number_rating = ratings_with_books.groupby("title")["rating"].count().reset_index().rename(columns={"rating":"no_of_rating"})

In [132]:
number_rating.head()

                                               title  no_of_rating
0   A Light in the Storm: The Civil War Diary of ...             2
1                              Always Have Popsicles             1
2               Apple Magic (The Collector's series)             1
3   Beyond IBM: Leadership Marketing and Finance ...             1
4   Clifford Visita El Hospital (Clifford El Gran...             1

In [133]:
ratings_with_books.head(2)

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc

In [134]:
number_rating.head(2)

                                               title  no_of_rating
0   A Light in the Storm: The Civil War Diary of ...             2
1                              Always Have Popsicles             1

In [135]:
final_rating = ratings_with_books.merge(number_rating, on="title")

In [136]:
final_rating.head(2)

,user_id,ISBN,rating,title,author,year,publisher,no_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82

In [137]:
final_rating.shape

(487671, 8)

In [140]:
final_rating = final_rating[final_rating.no_of_rating>=50]

In [141]:
final_rating.shape

(61853, 8)

Above is data of books ad users.

Each book have atleast 50 ratings.

Each user have given atleast 200 ratings.

In [146]:
any(final_rating[["user_id", "title"]].duplicated())

True

We can see there are some duplicated values

Let's drop them

In [147]:
final_rating[final_rating[["user_id", "title"]].duplicated()]

,user_id,ISBN,rating,title,author,year,publisher,no_of_rating
702,11676,0440977096,10,The Secret Garden,Frances Hodgson Burnett,1989,Laure Leaf,79
710,11676,0879236493,9,The Secret Garden,Frances Hodgson Burnett,1987,David R. Godine Publisher,79
717,35050,0439099390,0,The Secret Garden,Frances Hodgson Burnett,1999,Scholastic,79
721,174791,0439099390,0,The Secret Garden,Frances Hodgson Burnett,1999,Scholastic,79
722,230522,0439099390,0,The Secret Garden,Frances Hodgson Burnett,1999,Scholastic,79
...,...,...,...,...,...,...,...,...
223478,172030,0821744941,9,Dark Angel,Anna Grant,1994,Zebra Books,54
223483,153662,0505524147,0,Dark Angel,Cassandra Collins,2000,Love Spell,54
228875,113270,0743439651,0,Still Waters,Jennifer Lauck,2001,Atria,83
228876,162639,0743439651,0,Still Waters,Jennifer Lauck,2001,Atria,83
228884,185233,074350996X,0,Still Waters,Jennifer Lauck,2001,Simon &amp; Schuster Audio,83

Looks like 2003 rows of data are duplicated.

In [148]:
final_rating.drop_duplicates(["user_id", "title"], inplace=True)

In [149]:
final_rating.shape

(59850, 8)

In [151]:
61853 - 2003
# initially 61000 rows
# 2000 duplicated
# 59000 rows now

59850

In [152]:
book_pivot = final_rating.pivot_table(columns="user_id", index="title", values="rating")

In [153]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
book_pivot.shape

(742, 888)

This tells us that there are 742 books, and 888 users.

In [155]:
book_pivot.fillna(0, inplace=True)

In [156]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [157]:
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(book_pivot)

In [178]:
 book_sparse

<742x888 sparse matrix of type '<class 'numpy.float64'>'
	with 14942 stored elements in Compressed Sparse Row format>


<img src="">

In [159]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm="brute")

In [160]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [199]:
distances, suggestions = model.kneighbors(book_pivot.iloc[237,:].values.reshape(1, -1), n_neighbors=7)

In [200]:
distances

array([[ 0.        , 68.78953409, 69.5413546 , 72.64296249, 76.83098333,
        77.28518616, 77.3369252 ]])

In [203]:
suggestions

array([[237, 240, 238, 241, 184, 536, 291]])

In [205]:
book_pivot.iloc[suggestions[0]].index

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall', 'Jacob Have I Loved'],
      dtype='object', name='title')

In [179]:
book_pivot.loc["Harry Potter and the Chamber of Secrets (Book 2)"]

user_id
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    9.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Harry Potter and the Chamber of Secrets (Book 2), Length: 888, dtype: float64

In [195]:
np.where(book_pivot.index == "Harry Potter and the Chamber of Secrets (Book 2)")[0][0]

237

In [193]:
len(np.where(book_pivot.index == "Harryd the Chamber of Secrets (Book 2)")[0])

0

In [219]:
def get_recommendations(name, no_of_recommendations):
    num = np.where(book_pivot.index == name)[0]
    if len(num) == 0:
        print("No such book in list")
        return
    else:
        num = num[0]
    distances, suggestions = model.kneighbors(book_pivot.iloc[num,:].values.reshape(1, -1), n_neighbors=no_of_recommendations + 1)
    return list(book_pivot.iloc[suggestions[0][1:]].index)

In [229]:
recommended_list = get_recommendations("Animal Farm", 6)

In [230]:
recommended_list

['Exclusive',
 'Jacob Have I Loved',
 'Second Nature',
 'Pleading Guilty',
 'No Safe Place',
 "Foucault's Pendulum"]

In [231]:
final_rating.columns

Index(['user_id', 'ISBN', 'rating', 'title', 'author', 'year', 'publisher',
       'no_of_rating'],
      dtype='object')

In [226]:
final_rating.shape

(59850, 8)

In [232]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,no_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82

In [234]:
final_rating.to_csv(os.path.join(folder_path, "final_data.csv"))

In [235]:
import pickle

In [236]:
pickle.dump(model, open(os.path.join(folder_path, "model.pkl"), "wb"))